version: "3.4"

services:
  api:
    container_name: multexbot_api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
  
networks:
  default:
    external:
      name: spexchange

